version: '2'
services:
    delfos-app:
        image: delfos
        external_links:
            - delfos-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=delfos
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    delfos-mongodb:
        extends:
            file: mongodb.yml
            service: delfos-mongodb
